- name: Wazuh Server Config Setup
  hosts: WazuhServer
  tasks:
    - name: Allow port 443 (https)
      shell: 'firewall-cmd --permanent --add-port=443/tcp && firewall-cmd --permanent --add-port=55000/tcp && firewall-cmd --permanent --add-port=1515/tcp && firewall-cmd --permanent --add-port=1514/tcp'
      become: yes

    - name: Curl Wazuh Install Script
      shell: "curl -sO https://packages.wazuh.com/4.3/wazuh-install.sh"
      become: yes 
    
    - name: Run Installer
      shell: 'cd /home/{{ ansible_user }}/ && bash ./wazuh-install.sh -a -i'
      become: yes

    - name: Tar the file for the Wazuh Password
      shell: tar -O -xvf wazuh-install-files.tar wazuh-install-files/wazuh-passwords.txt
      become: yes

    - name: Enable Wazuh 
      shell: "systemctl enable wazuh-indexer-performance-analyzer && systemctl start wazuh-indexer-performance-analyzer"
      become: yes

    - name: Reboot
      shell: "sleep 5 && reboot"
      become: yes
      async: 1
      poll: 0
